# Generated by Django 4.2.3 on 2024-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_price_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture_category',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='изображение'),
        ),
    ]
